services:
  app:
    container_name: warehouse-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .app.env
    networks:
      - warehouse-network
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: warehouse-postgres
    image: postgres:16-alpine
    env_file:
      - .postgres.env
    ports:
      - "5433:5432"
    networks:
      - warehouse-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  test:
    container_name: warehouse-tests
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .test.env
    networks:
      - warehouse-network
    volumes:
      - ./test-results:/tmp/results
    depends_on:
      - postgres-test
    profiles: [ "test" ]

  postgres-test:
    container_name: warehouse-postgres-test
    image: postgres:16-alpine
    env_file:
      - .postgres-test.env
    networks:
      - warehouse-network
    profiles: [ "test" ]

networks:
  warehouse-network:
    driver: bridge

volumes:
  pg_data:
